"""add feature store tables and run feature_set_id

Revision ID: 40ae8d489ea7
Revises: ac8126d47dcc
Create Date: 2026-04-08 14:40:42.365078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40ae8d489ea7'
down_revision: Union[str, Sequence[str], None] = 'ac8126d47dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_sets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('feature_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.String(length=5), server_default='true', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_feature_set_name_version', 'feature_sets', ['name', 'version'], unique=True)
    op.create_table('feature_store_registry',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('feature_set_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['feature_set_id'], ['feature_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('runs', sa.Column('feature_set_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'runs', 'feature_sets', ['feature_set_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.drop_column('runs', 'feature_set_id')
    op.drop_table('feature_store_registry')
    op.drop_index('uq_feature_set_name_version', table_name='feature_sets')
    op.drop_table('feature_sets')
    # ### end Alembic commands ###
