"""add model registry tables

Revision ID: 709dd7b99f79
Revises: 40ae8d489ea7
Create Date: 2026-04-08 15:31:36.035914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '709dd7b99f79'
down_revision: Union[str, Sequence[str], None] = '40ae8d489ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registered_models',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=20), server_default='development', nullable=True),
    sa.Column('stage_changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('stage_changed_by', sa.String(length=50), server_default='api', nullable=True),
    sa.Column('s3_artifact_path', sa.String(length=500), nullable=True),
    sa.Column('model_size_mb', sa.Float(), nullable=True),
    sa.Column('metrics_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['registered_models.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_model_version', 'model_versions', ['model_id', 'version'], unique=True)
    op.create_table('model_stage_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('from_stage', sa.String(length=20), nullable=False),
    sa.Column('to_stage', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_stage_history')
    op.drop_index('uq_model_version', table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_table('registered_models')
    # ### end Alembic commands ###
