"""add drift_reports table

Revision ID: d231c196b5a2
Revises: 709dd7b99f79
Create Date: 2026-04-08 15:43:14.358864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd231c196b5a2'
down_revision: Union[str, Sequence[str], None] = '709dd7b99f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drift_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('reference_dataset_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=30), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('overall_drift_score', sa.Float(), nullable=True),
    sa.Column('is_drifted', sa.String(length=5), server_default='false', nullable=True),
    sa.Column('feature_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['reference_dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drift_reports')
    # ### end Alembic commands ###
